// @generated by protoc-gen-es v2.14.1 with parameter "target=ts,import_extension=js"
// @generated from file admiral/common/v1/actor.proto (package admiral.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admiral/common/v1/actor.proto.
 */
export const file_admiral_common_v1_actor: GenFile = /*@__PURE__*/
  fileDesc("Ch1hZG1pcmFsL2NvbW1vbi92MS9hY3Rvci5wcm90bxIRYWRtaXJhbC5jb21tb24udjEiOwoIQWN0b3JSZWYSCgoCaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJQk9aTWJ1Zi5idWlsZC9nZW4vZ28vYWRtaXJhbC9jb21tb24vcHJvdG9jb2xidWZmZXJzL2dvL2FkbWlyYWwvY29tbW9uL3YxO2NvbW1vbnYxYgZwcm90bzM");

/**
 * ActorRef is a lightweight reference to the user or agent that performed an action.
 * Server-populated on all resource responses. Clients should never send this;
 * use the plain string `created_by` UUID on request messages instead.
 *
 * @generated from message admiral.common.v1.ActorRef
 */
export type ActorRef = Message<"admiral.common.v1.ActorRef"> & {
  /**
   * UUID of the user or service access token.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable name (e.g., "John Smith", "cluster-prod-agent").
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Email address (empty for non-human actors).
   *
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message admiral.common.v1.ActorRef.
 * Use `create(ActorRefSchema)` to create a new message.
 */
export const ActorRefSchema: GenMessage<ActorRef> = /*@__PURE__*/
  messageDesc(file_admiral_common_v1_actor, 0);

