// Code generated by protorepo protoc-gen-scopes. DO NOT EDIT.
//
// Source of truth: the scopes/sat_profiles catalog in protorepo.yaml and the
// (admiral.common.v1.authz) method options. Scopes are a reduction mechanism
// over live authorization, never additive.

/**
 * The scope claim carried by unreduced first-party tokens: no reduction over
 * live authorization. Never mintable input and never a catalog entry. Absence
 * of a scope claim means DENY, not unrestricted.
 */
export const WILDCARD = "*";

/**
 * Credential types, as used in Scope.assignableTo: which credential a scope
 * may be attached to when one is issued.
 */
export const TokenType = {
  PAT: "pat",
  SAT: "sat",
} as const;
export type TokenType = (typeof TokenType)[keyof typeof TokenType];

/**
 * Principal kinds, matched against the `kind` claim on an STS-minted token.
 * A different vocabulary from the credential types above: `kind` describes
 * the principal, not the credential presented. A browser session, a CLI login
 * and a PAT are all "user"; every machine identity is "serviceaccount".
 */
export const Kind = {
  User: "user",
  ServiceAccount: "serviceaccount",
} as const;
export type Kind = (typeof Kind)[keyof typeof Kind];

/** Scope names, so a client never spells one by hand. */
export const Scopes = {
  AgentDeploy: "agent:deploy",
  AgentExec: "agent:exec",
  AgentRead: "agent:read",
  AgentStatus: "agent:status",
  AgentWrite: "agent:write",
  AppRead: "app:read",
  AppWrite: "app:write",
  ComponentPublish: "component:publish",
  ComponentRead: "component:read",
  ComponentWrite: "component:write",
  CredentialRead: "credential:read",
  CredentialWrite: "credential:write",
  EnvRead: "env:read",
  EnvWrite: "env:write",
  RunRead: "run:read",
  RunWrite: "run:write",
  SourceRead: "source:read",
  SourceWrite: "source:write",
  TenantRead: "tenant:read",
  TenantWrite: "tenant:write",
  TokenRead: "token:read",
  TokenWrite: "token:write",
  UserRead: "user:read",
  UserWrite: "user:write",
  VarRead: "var:read",
} as const;
export type ScopeName = (typeof Scopes)[keyof typeof Scopes];

/** One scope prefix and what it covers: "app" for app:read and app:write. */
export interface Group {
  readonly name: string;
  readonly description: string;
}

/** Every group, in catalog order. Every scope's prefix has one. */
export const GROUPS: readonly Group[] = [
  { name: "agent", description: "Execution agents, their tokens, and the jobs and workloads they run." },
  { name: "app", description: "Applications and their change sets." },
  { name: "component", description: "The component registry, where published Terraform modules, Helm charts and manifests live." },
  { name: "credential", description: "Credentials for external systems." },
  { name: "env", description: "Deployment environments and the components in them." },
  { name: "run", description: "Runs of change sets, plan through apply." },
  { name: "source", description: "External artifact sources." },
  { name: "tenant", description: "Your tenant." },
  { name: "token", description: "Your own API keys." },
  { name: "user", description: "Members of your tenant." },
  { name: "var", description: "Configuration variables." },
];

/** Group name to its definition. */
export const GROUP_BY_NAME: Readonly<Record<string, Group>> = Object.fromEntries(
  GROUPS.map((g) => [g.name, g]),
);

/** The group a scope name falls under: everything before the first colon. */
export function groupOf(scope: string): string {
  const i = scope.indexOf(":");
  return i < 0 ? scope : scope.slice(0, i);
}

/** One catalog entry. */
export interface Scope {
  readonly name: string;
  readonly description: string;
  /** Directly implied scopes; see covers() for transitive coverage. */
  readonly implies: readonly string[];
  /**
   * Mint-time policy: the credential types this scope may be attached to.
   * Empty means mintable by nothing: the scope guards an RPC and no
   * credential a person can create may carry it. Check it before offering
   * a scope in a form.
   */
  readonly assignableTo: readonly TokenType[];
}

/** Every scope, in catalog order. */
export const SCOPES: readonly Scope[] = [
  {
    name: "agent:deploy",
    description: "Fetch revision bundles and report revision results.",
    implies: [],
    assignableTo: ["sat"],
  },
  {
    name: "agent:exec",
    description: "Agent runtime job execution — heartbeat, claim jobs, fetch job bundles, and report job results.",
    implies: [],
    assignableTo: ["sat"],
  },
  {
    name: "agent:read",
    description: "Read agents, agent tokens, jobs, workloads, and workload events.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "agent:status",
    description: "Report agent status, workload status, and workload metrics.",
    implies: [],
    assignableTo: ["sat"],
  },
  {
    name: "agent:write",
    description: "Create, update, and delete agents; manage agent tokens and identity bindings.",
    implies: ["agent:read"],
    assignableTo: ["pat"],
  },
  {
    name: "app:read",
    description: "Read applications, change sets, and change set diffs.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "app:write",
    description: "Create, update, and delete applications; manage change sets and their entries and variables.",
    implies: ["app:read"],
    assignableTo: ["pat"],
  },
  {
    name: "component:publish",
    description: "Publish revisions and set tags. Adds to the registry and removes nothing from it, which is what a CI publish key holds.",
    implies: ["component:read"],
    assignableTo: ["pat"],
  },
  {
    name: "component:read",
    description: "Read components, their revisions and tags, and the contract and findings each revision carries.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "component:write",
    description: "Edit a component's metadata, retire components, deprecate revisions, and delete floating tags, in addition to everything a publisher can do.",
    implies: ["component:publish"],
    assignableTo: ["pat"],
  },
  {
    name: "credential:read",
    description: "Read credentials.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "credential:write",
    description: "Create, update, and delete credentials.",
    implies: ["credential:read"],
    assignableTo: ["pat"],
  },
  {
    name: "env:read",
    description: "Read environments and their components.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "env:write",
    description: "Create, update, and delete environments.",
    implies: ["env:read"],
    assignableTo: ["pat"],
  },
  {
    name: "run:read",
    description: "Read runs and revisions.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "run:write",
    description: "Create, apply, and cancel runs; retry revisions.",
    implies: ["run:read"],
    assignableTo: ["pat"],
  },
  {
    name: "source:read",
    description: "Read sources and source versions.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "source:write",
    description: "Create, update, delete, and test sources.",
    implies: ["source:read"],
    assignableTo: ["pat"],
  },
  {
    name: "tenant:read",
    description: "Read the caller's own tenant -- name, slug, and status.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "tenant:write",
    description: "Update the caller's own tenant's settings, and close it -- suspending or deleting the tenant you own. Which of those you may actually do is decided per tenant, not by holding this.",
    implies: ["tenant:read"],
    assignableTo: ["pat"],
  },
  {
    name: "token:read",
    description: "Read your own API keys.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "token:write",
    description: "Create, update, and revoke your own API keys.",
    implies: ["token:read"],
    assignableTo: ["pat"],
  },
  {
    name: "user:read",
    description: "Read user profiles within your own tenant.",
    implies: [],
    assignableTo: ["pat"],
  },
  {
    name: "user:write",
    description: "Create users and manage their access -- suspending, reactivating, or offboarding them. Reach is decided per tenant rather than by holding this, so the same scope covers adding someone to your own tenant and an operator acting across the platform.",
    implies: ["user:read"],
    assignableTo: ["pat"],
  },
  {
    name: "var:read",
    description: "Read resolved environment variables, including secret values.",
    implies: [],
    assignableTo: ["pat"],
  },
];

/** Scope name to its definition. */
export const CATALOG: Readonly<Record<string, Scope>> = Object.fromEntries(
  SCOPES.map((s) => [s.name, s]),
);

const impliesClosure: Readonly<Record<string, readonly string[]>> = {
  "agent:write": ["agent:read"],
  "app:write": ["app:read"],
  "component:publish": ["component:read"],
  "component:write": ["component:publish", "component:read"],
  "credential:write": ["credential:read"],
  "env:write": ["env:read"],
  "run:write": ["run:read"],
  "source:write": ["source:read"],
  "tenant:write": ["tenant:read"],
  "token:write": ["token:read"],
  "user:write": ["user:read"],
};

/**
 * Whether a token's scope set covers the required scope: the wildcard,
 * direct membership, or a transitively implied scope. Says nothing about
 * live authorization; a covering scope set still goes through the FGA check.
 */
export function covers(tokenScopes: readonly string[], required: string): boolean {
  for (const s of tokenScopes) {
    if (s === WILDCARD || s === required) {
      return true;
    }
    if (impliesClosure[s]?.includes(required)) {
      return true;
    }
  }
  return false;
}

/** The scopes a credential of the given type may carry, in catalog order. */
export function assignableTo(tokenType: TokenType): readonly Scope[] {
  return SCOPES.filter((s) => s.assignableTo.includes(tokenType));
}
